version: "3.9"

services:
  geo_stac_fastapi:
    build:
      context: ./
      dockerfile: Dockerfile
    hostname: geo_stac_fastapi
    container_name: geo_stac_fastapi
    depends_on:
      geo_stac_postgres:
        condition: service_healthy
    ports:
      - "8000:8000"
    environment:
      - DOCKER_ENV=1

  geo_stac_postgres:
    image: postgis/postgis:15-3.4-alpine
    hostname: geo_stac_postgres
    container_name: geo_stac_postgres
    restart: on-failure
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - db-postgres:/var/lib/postgresql/data
      - ./scripts/database_setup.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-postgres:
    driver: local